version: '3.4'

services:
  nes-build-container:
    build: .
    container_name: nes-build-container
    hostname: nes-build-container
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./src:/src
      - ./data:/data